"""
Todo API endpoints.
Handles CRUD operations for todo items.
"""

from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlmodel import Session, select
from typing import Optional

from ...config.database import get_engine
from ...models.todo import Todo, TodoStatus, TodoPriority
from ...models.user import User
from ...schemas.todo import (
    TodoCreate,
    TodoUpdate,
    TodoResponse,
    TodoListResponse
)
from .auth import get_current_user

router = APIRouter()


@router.get("/", response_model=TodoListResponse)
def get_todos(
    skip: int = Query(0, ge=0, description="Number of items to skip"),
    limit: int = Query(100, ge=1, le=100, description="Max items to return"),
    status_filter: Optional[TodoStatus] = Query(None, alias="status"),
    priority: Optional[TodoPriority] = Query(None),
    current_user: User = Depends(get_current_user)
):
    """
    Get all todos for the current user.
    
    Args:
        skip: Pagination offset
        limit: Maximum number of items
        status_filter: Filter by status
        priority: Filter by priority
        current_user: Authenticated user
        
    Returns:
        List of todos with pagination
    """
    engine = get_engine()
    
    with Session(engine) as session:
        # Build query
        statement = select(Todo).where(Todo.user_id == current_user.id)
        
        # Apply filters
        if status_filter:
            statement = statement.where(Todo.status == status_filter)
        if priority:
            statement = statement.where(Todo.priority == priority)
        
        # Get total count
        count_statement = select(Todo).where(Todo.user_id == current_user.id)
        if status_filter:
            count_statement = count_statement.where(Todo.status == status_filter)
        if priority:
            count_statement = count_statement.where(Todo.priority == priority)
        
        total = session.exec(count_statement).count()
        
        # Apply pagination
        statement = statement.offset(skip).limit(limit)
        todos = session.exec(statement).all()
        
        return TodoListResponse(
            items=[TodoResponse.from_orm(todo) for todo in todos],
            total=total,
            limit=limit,
            offset=skip
        )


@router.post("/", response_model=TodoResponse)
def create_todo(
    todo_data: TodoCreate,
    current_user: User = Depends(get_current_user)
):
    """
    Create a new todo item.

    Args:
        todo_data: Todo creation data
        current_user: Authenticated user

    Returns:
        Created todo item
    """
    engine = get_engine()

    with Session(engine) as session:
        # Create todo - ID is auto-generated by the model
        todo = Todo(
            title=todo_data.title,
            description=todo_data.description,
            status=todo_data.status,
            priority=todo_data.priority,
            due_date=todo_data.due_date,
            user_id=current_user.id
        )

        session.add(todo)
        session.commit()
        session.refresh(todo)

        return TodoResponse.from_orm(todo)


@router.get("/{todo_id}", response_model=TodoResponse)
def get_todo(
    todo_id: str,
    current_user: User = Depends(get_current_user)
):
    """
    Get a specific todo by ID.
    
    Args:
        todo_id: Todo item ID
        current_user: Authenticated user
        
    Returns:
        Todo item
        
    Raises:
        HTTPException: If todo not found or not owned by user
    """
    engine = get_engine()
    
    with Session(engine) as session:
        statement = select(Todo).where(
            Todo.id == todo_id,
            Todo.user_id == current_user.id
        )
        todo = session.exec(statement).first()
        
        if not todo:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Todo not found"
            )
        
        return TodoResponse.from_orm(todo)


@router.put("/{todo_id}", response_model=TodoResponse)
def update_todo(
    todo_id: str,
    todo_update: TodoUpdate,
    current_user: User = Depends(get_current_user)
):
    """
    Update a todo item.
    
    Args:
        todo_id: Todo item ID
        todo_update: Update data
        current_user: Authenticated user
        
    Returns:
        Updated todo item
        
    Raises:
        HTTPException: If todo not found or not owned by user
    """
    engine = get_engine()
    
    with Session(engine) as session:
        # Find todo
        statement = select(Todo).where(
            Todo.id == todo_id,
            Todo.user_id == current_user.id
        )
        todo = session.exec(statement).first()
        
        if not todo:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Todo not found"
            )
        
        # Update fields (using dict() for Pydantic v1 compatibility)
        update_data = todo_update.dict(exclude_unset=True)
        for field, value in update_data.items():
            setattr(todo, field, value)
        
        # Auto-set completed_at when status changes to completed
        if todo_update.status == TodoStatus.completed and todo.completed_at is None:
            from datetime import datetime
            todo.completed_at = datetime.utcnow()
        
        session.add(todo)
        session.commit()
        session.refresh(todo)
        
        return TodoResponse.from_orm(todo)


@router.delete("/{todo_id}")
def delete_todo(
    todo_id: str,
    current_user: User = Depends(get_current_user)
):
    """
    Delete a todo item.
    
    Args:
        todo_id: Todo item ID
        current_user: Authenticated user
        
    Returns:
        Success message
        
    Raises:
        HTTPException: If todo not found or not owned by user
    """
    engine = get_engine()
    
    with Session(engine) as session:
        # Find todo
        statement = select(Todo).where(
            Todo.id == todo_id,
            Todo.user_id == current_user.id
        )
        todo = session.exec(statement).first()
        
        if not todo:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Todo not found"
            )
        
        # Delete todo
        session.delete(todo)
        session.commit()
        
        return {"message": "Todo deleted successfully"}
